### ISSUE TITLE
Uma Idéia

### ISSUE THREAD

**Issue by KomashiFX** [SaphireBot/SaphireV14#2]
colocar um readme com mais detalhes sobre o bot.

> eu ate consigo ajudar se for necessário.

**Comment by Gorniaky** [comment]
realmente, @rodycouto

**Comment by rodycouto** [comment]
Terminar o BETA e faço o Read.me

**Comment by Gorniaky** [comment]
> Terminar o BETA e faço o Read.me

Então ainda vai demorar, visto que falta migrar pra typescript

**Comment by KomashiFX** [comment]
ficarei no aguardo até lá, quando finalizar já sabes meu discord, ai eu faço a boa no readme

**Comment by rodycouto** [comment]
> ficarei no aguardo até lá, quando finalizar já sabes meu discord, ai eu faço a boa no readme

Não sei seu Discord, mas se você quiser fazer o read.me,  os créditos serão 100% seus.

**Comment by KomashiFX** [comment]
eu havia confundido kdkldlaskjkdjska teu nome  e idêntico a de um amigo, mas meu discord e esse aqui > **komashi#1714**.

Só me dizer tudo que devo escrever no readme que eu monto ele e gg
